### ISSUE TITLE
[BUG] Viewer for cached documents is broken (regression)

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#1551]
## Description

Neither the calendar view nor the document view works for cached METS files.

## Reproduction

Steps to reproduce the behaviour:

1. Run the viewer with `tx_dlf[id]=URL`. This works fine.
2. Run the viewer with `tx_dlf[id]=ID`. This does not show anything.

This issue might be related to incomplete caching. See also [my comment](https://github.com/kitodo/kitodo-presentation/pull/1536#issuecomment-2732864469).

**Comment by stweil** [comment]
> 2\. This does not show anything.

... or more correct, it does not show anything reasonable. For a text document this is shown on the left side (and similar on the right side):

<img width="187" alt="Bildschirmfoto 2025-03-18 um 12 30 54" src="https://github.com/user-attachments/assets/99f63a7b-ec93-4fd9-bd03-83da1012837b" />

**Comment by stweil** [comment]
Note that the regression mentioned in https://github.com/kitodo/kitodo-presentation/pull/1523#issuecomment-2746250164 is a different issue.

**Comment by stweil** [comment]
This is a critical bug. How can we get it fixed?

**Comment by stweil** [comment]
The latest code no longer shows the musical symbol, but still no view with a numeric id works. See my [test installation](https://digital.ladenburg.world/) where Ladenburger Wochenblatt was indexed (and therefore does not work) while Neckar-Bergstraß-Post was not indexed (and works).

This makes Kitodo.Presentation basically unusable.

@sebastian-meyer, @beatrycze-volk, do you have any idea what I could do?

**Comment by beatrycze-volk** [comment]
It could be related to my latest changes in https://github.com/kitodo/kitodo-presentation/pull/1636 

Maybe some adjustments in sleep/wake functions are necessary after I have adjusted constructor.

**Comment by beatrycze-volk** [comment]
https://github.com/kitodo/kitodo-presentation/pull/1679 adjusts the sleep/wake functions, caching should work again.

**Comment by sebastian-meyer** [comment]
@stweil Can you confirm that this is fixed?

**Comment by stweil** [comment]
It works for 5.1.x, but I still have to update my main branch based installation for a new test.

**Comment by stweil** [comment]
@sebastian-meyer, I get a new Oops for cached and uncached documents with the latest main branch:

```
Wed, 20 Aug 2025 17:58:27 +0200 [ALERT] request="6427e3c4d2db7" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 2025082017582630f11ba3- Exception: Kitodo\Dlf\Domain\Repository\DocumentRepository::getChildrenOfYearAnchor(): Argument #1 ($partOf) must be of type int, null given, called in /var/customers/webs/weil/viewer/vendor/kitodo/presentation/Classes/Controller/CalendarController.php on line 162 [...]
```

@beatrycze-volk, this regression might be caused by this commit:

```
200489788b418649f8d435cfb2429d3cc1733eb4 is the first bad commit
commit 200489788b418649f8d435cfb2429d3cc1733eb4 (HEAD)
Author: Beatrycze Volk <beatrycze.volk@slub-dresden.de>
Date:   Mon Jun 16 16:21:53 2025 +0200

    [MAINTENANCE] Adjust SQL queries (#1637)
    
    Co-authored-by: Sebastian Meyer <sebastian.meyer@opencultureconsulting.com>

 .github/phpstan.neon                               |   1 -
 Classes/Command/BaseCommand.php                    |   2 +-
 Classes/Common/AbstractDocument.php                |  16 +++++++--------
 Classes/Common/Helper.php                          |   6 +++---
 Classes/Common/Indexer.php                         |  20 +++++++++----------
 Classes/Common/MetsDocument.php                    |  22 ++++++++++-----------
 Classes/Common/Solr/Solr.php                       |  14 ++++++-------
 Classes/Domain/Repository/CollectionRepository.php |  12 +++++------
 Classes/Domain/Repository/DocumentRepository.php   | 164 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------------------------
 Classes/Hooks/DataHandler.php                      |   4 ++--
 10 files changed, 128 insertions(+), 133 deletions(-)
```

**Comment by stweil** [comment]
> [@stweil](https://github.com/stweil) Can you confirm that this is fixed?

It is only partially fixed. The calendar views for years and months work fine, but the document view still does not work for cached METS files (see [example](https://digital.ladenburg.world/viewer?tx_dlf[id]=2865)).

**Comment by stweil** [comment]
@beatrycze-volk, @sebastian-meyer, in my tests with the latest main branch, the document view now works again with a METS URL, but not with a numeric document id. I see no errors or warning in the log files. Do you have a suggestion what I could try next?

~Unrelated: my Kitodo search does not find any document, although the Solr core contains fulltext and other metadata. It works fine in my 5.1.x installation. Is the search broken in the latest code? [OAI-PMH](https://digital.ladenburg.world/oai/?verb=Identify) seems to work fine and shows all indexed documents. See more details in the discussion #1699.~ This is solved now, see discussion for #1701.

**Comment by stweil** [comment]
This really very essential functionality is still broken in the very latest code of kitodo-presentation / dfgviewer / slub-digitalcollections. I still have no idea where to look for a solution. :-(

@thomaslow, does the document viewer in your typo3-v13-support branch work with numeric ids?

**Comment by thomaslow** [comment]
@stweil I can view documents in #1686 with the demo theme by specifying a number as the `tx_dlf[id]` parameter, e.g.:

`http://localhost:8080/detail?tx_dlf[id]=51`

The image of the page is shown. 

When I started working on the Typo3 v13 update, my viewer didn't show any images because of #1682. After that it worked for me without any issues.

**Comment by stweil** [comment]
Thanks for this hint. The main branch which includes this patch does not fix this issue for me, and nor does an update to your typo3-v13-support branch which I just tried with TYPO3 v12 where it can be combined with dfgviewer. But at least I can confirm that your branch works otherwise fine without new issues up to now.

Maybe the issue occurs only with the combination of kitodo-presentation and dfgviewer?

**Comment by thomaslow** [comment]
@stweil I was curious and set up the DFG Viewer (current master). I indexed the document: 

- https://digital.slub-dresden.de/data/kitodo/FhrZehn_1822844975/FhrZehn_1822844975_mets.xml
- https://digital.slub-dresden.de/data/kitodo/FhrZehn_182284648X_0001/FhrZehn_182284648X_0001_mets.xml
- https://digital.slub-dresden.de/data/kitodo/FhrZehn_1822847370_0002/FhrZehn_1822847370_0002_mets.xml

When opening the DFG viewer by specifying the document UID, the viewer is empty.

The reason seems to be that the DFG viewer setting for `multiViewType` defaults to the value `composition`, see [kitodo.typoscript](https://github.com/slub/dfg-viewer/blob/27ea9dc92cac2d191252802f4400dcef0042e490/Configuration/TypoScript/Plugins/kitodo.typoscript#L133).

However, the multi-view mode only seems to be supported if the document's table of contents `type` attribute matches that setting. In my case, the documents above have a table of contents type of `multivolume_work`. Because of that, the multi-view mode does not work. 

Unfortunately, this is only detected at later stage, preventing the fallback to the default viewer mode.

You could try to disable the multi-view mode by settings `multiViewType` to an empty string, or enable it by adjusting the value to the correct TOC type value.

In the short term, I think we should refactor the code around the multi-view mode detection. At the moment, there are several `if` statements checking for multi-view mode support with different conditions (sometimes checking for the TOC type requirement, sometimes not).

**Comment by stweil** [comment]
@thomaslow, many thanks! A [small patch for slub/dfgviewer](https://github.com/stweil/dfg-viewer/commit/704ce7e7ac4b1f7f685595edd15b57bf9c777c89) solved the broken viewer now.

**Comment by stweil** [comment]
@sebastian-meyer, how should this issue really be fixed? Are you planning to release a patch for slub/dfgviewer? As mentioned earlier, there are still some weaknesses in the current Kitodo code.

**Comment by sebastian-meyer** [comment]
Although implementation of multiview can certainly be improved, this particular issue is not a bug in Kitodo.Presentation. It's an issue with default configuration of slub/dfg-viewer (which is not yet up-to-date with latest changes in Kitodo). Without slub/dfg-viewer addressing a document by its ID works just fine.

That's why I closed this issue.

**Comment by fschoelzel** [comment]
Can confirm specifying a number as the tx_dlf[id] parameter works with `6.x`.

This Issue got also adjusted in slub_digitalcollctions by @beatrycze-volk here: https://github.com/slub/slub_digitalcollections/commit/377d0283b35d12c550c5ae3359ee0c6237eff271
